name: Xamarin.Android

on: [push]

jobs:
  build:
    name: Build ðŸ› 
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore UITestDemo.sln

    - name: Build
      run: msbuild ${{GitHub.Workspace}}/Droid/UITestDemo.Droid.csproj /t:PackageForAndroid /p:Configuration=Debug
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: android
        path: ${{GitHub.Workspace}}/Droid/bin/Debug/com.appcenter.UITestDemo.apk
